name: Deploy do Compressor PDF Online

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar o repositório
        uses: actions/checkout@v3

      - name: 🚀 Fazer deploy da pasta compressor-pdf-online para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./compressor-pdf-online
          publish_branch: gh-pages
          force_orphan: true
